name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn

      - name: Running Build
        run: yarn workspaces run build

      - name: Running Test With Coverage
      - run: yarn test --coverage

      - name: Bump Coverage to codecov
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 98cfb3ef-e3ad-4ffc-aaa1-314731222d1b

    eslint:
      name: ESlint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master

        - name: Set Node.js 10.x
          uses: actions/setup-node@master
          with:
            node-version: 10.x

        - name: Cache Dependencies
          uses: actions/cache@v1
          with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

        - name: Install Dependencies
          run: yarn

        - name: Running ESLint
          run: yarn eslint .
