name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - ".vscode/**"

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  install-build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.4
          run_install: true

      - name: Use latest version of Node.j
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "pnpm"

      - name: Build packages
        run: pnpm build

      - name: Build DnD React App
        run: pnpm -F dflex-react-dnd build:app

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            packages/core-instance/dist
            packages/utils/dist
            packages/dom-gen/dist
            packages/draggable/dist
            packages/store/dist
            packages/dnd/dist
            packages/dnd/playgrounds/dflex-react-dnd/dist
          if-no-files-found: error

  cypress-same-container-horizontal:
    name: test-e2e-horizontal
    runs-on: ubuntu-latest
    timeout-minutes: 8
    if: github.event.pull_request.draft != true
    needs: install-build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.4
          run_install: true

      - name: Use latest version of Node.j
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "pnpm"

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Display structure of downloaded files
        run: ls -R

      - name: Testing all features for DnD with React APP - Chrome
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: packages/dnd
          spec: cypress/integration/same-container-horizontal/**/*.spec.ts
          start: pnpm -F dflex-react-dnd preview
          wait-on: "http://localhost:3001/"
          wait-on-timeout: 30
          browser: chrome
          headless: true
        env:
          Cypress_extended: true
