name: "size"

on:
  pull_request:
    branches:
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action@v2
      - uses: andresz1/size-limit-action@master
        with:
          package_manager: pnpm
          limit: 100kb
