name: "size"

on:
  pull_request:
    branches:
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@dd31dce7dcc72a041fd3e49abf0502b13fc4ce05
        with:
          package_manager: pnpm
          limit: 100kb
