name: "size"

on:
  pull_request:
    branches:
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'dflex-js' && github.event.pull_request.draft != true
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ^8.0.0
          run_install: true
      - uses: andresz1/size-limit-action@dd31dce7dcc72a041fd3e49abf0502b13fc4ce05
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          build_script: "build-prod"
